export const siteConfig = {
  name: "Create T3 App",
  description: "Generated by create-t3-app",
  url: "http://localhost:3000",
  ogImage: "http://localhost:3000/og.png",
};

export type SiteConfig = typeof siteConfig;
